### PR TITLE
Mark system headers

### PR DESCRIPTION
**Pull request by mathstuf**
---
@yumin @vibraphone

### CODE REVIEW

**Comment by yumin** [comment]
@vibraphone David, you will be the better person to comment on this.

**Comment by vibraphone** [comment]
I don't have permission to push new commits to this PR. See [this branch (vibraphone/mark-system-headers)](https://github.com/vibraphone/SMTK/tree/mark-system-headers) for a commit required to get things working for me on Mac OS X with clang. This PR alone does not appear to mask warnings.

**Comment by yumin** [comment]
@mathstuf ping...

**Comment by mathstuf** [comment]
I cherry-picked @vibraphone's commit.

**Comment by vibraphone** [comment]
+2

**Pull request merged**
