### PR TITLE
cmake: don't override the main variable for shared libs

### PR DESCRIPTION
**Pull request by mathstuf**
Upstream commit ea0c5c1fab1c1c16c5bbe02ff6069fdd1261485f

---
@robertmaynard @vibraphone

### CODE REVIEW

**Comment by vibraphone** [comment]
+1, but this should also be upstreamed to MOAB.

**Comment by mathstuf** [comment]
It has been sent upstream (hence the upstream commit hash).

**Comment by robertmaynard** [comment]
Are we happy with merging this in?

**Comment by vibraphone** [comment]
> Are we happy with merging this in?

That's why I said +1.

**Pull request merged**
