### PR TITLE
Python directories

### PR DESCRIPTION
**Pull request by mathstuf**
---
@vibraphone 

Untested other than Linux, but it is *much* better there now :) .

### CODE REVIEW

**Comment by mathstuf** [comment]
Updated.

**Comment by vibraphone** [comment]
+1. Merge away.

**Comment by mathstuf** [comment]
Hmm. What's the process for getting branches into `release-v1`?

**Comment by vibraphone** [comment]
You should be able to do a PR against release-v1. From what Bob has said, he wants smtk::mesh in v1, so really all of master needs to be merged into release-v1. But nothing should be merged into the release-v1 branch until CMB (and maybe data-browser and eventually SimMedTK) will build with it properly.

**Comment by yumin** [comment]
To update release-v1, checkout a local branch of origin/release-v1, merge origin/master into it, push that to your fork, then create PR against origin/release-v1.

Like Dave said, I believe the "rootView" changes in smtk will break CMB at least, so until CMB gets compatible changes, release-v1 should not be moved. I don't know what branch/tag data-browser or SimMedTK is using for smtk, or whether they need to be updated.

**Comment by vibraphone** [comment]
SimMedTK doesn't include SMTK in master yet (but has a PR to integrate it). So don't worry about it yet. But soon, it will also rely on SMTK and merging significant changes from master into release branches will generate frowny-faces.

**Comment by mathstuf** [comment]
Is this still good to go?

**Comment by yumin** [comment]
I don't think anything has changed in master related to this. You may want to rebase on master through, and if travis is still ok, +2 from me. (btw, David is on vac I believe).

**Pull request merged**
