### PR TITLE
New universal close model operator

### PR DESCRIPTION
**Pull request by yumin**
Adding capability to close models individually in sessions. This includes removing the model related records from smtk and the actual model from the modeling kernel.

### CODE REVIEW

**Comment by yumin** [comment]
@vibraphone

**Comment by vibraphone** [comment]
It would be great to add `CloseModel` to `smtk/smtk/simple.py` along the same lines as the other operators, and then update the test to use it instead of the low-level operator API. See the `smtk/bridge/cgm/testing/python/cgmBooleans.py` python test for an example of the simple API.

**Comment by vibraphone** [comment]
Also, see #96 for a related feature request. This operator "closes" the SMTK side of things but does not call anything on the underlying modeling kernel asking it to delete a model/body.

**Comment by yumin** [comment]
I thought (Should it?) Manager::eraseModel() should handle things like that.

**Comment by vibraphone** [comment]
> I thought (Should it?) Manager::eraseModel() should handle things like that.

Nope, it only changes things in the SMTK model manager. The SMTK design principle is that only operators interact with the modeling kernels; the model manager should not.

**Comment by yumin** [comment]
How about add a method in Session class
Session::unloadModel(UUID)
which in base class we just do smtk::model::Manager::eraseModel(), and in each different sessions (discrete, cgm, exodus, etc) we can override unloadModel(UUID) to do kernel specific stuff.

**Comment by vibraphone** [comment]
@yumin That would violate SMTK's design principle. If it is impossible to have this operator registered with the Session base class **plus** operators of the same name for the CGM and discrete Sessions, then we can create kernel-specific operators with different names and have this operator invoke them internally. But no method on the model Session or Manager classes should call functions on the modeling kernel.

**Comment by yumin** [comment]
@vibraphone 
I tried quickly with discrete session, and it is not possible to register operators with the same name in both base-Session and discrete-session.

In terms of design, I did mean to call Session::unloadModel() inside the CloseModel operator, like this,
closeOp->session()->unloadModel().
I was actually thinking making Session::unloadModel() protected. To me, this is similar to what "read" or "import" operator is doing, except it is in Session base.

**Comment by vibraphone** [comment]
@yumin Do not do it that way. Instead, make an "unload model" operator and invoke it from within the "close model" operator. I am strongly opposed to having methods on Session or Manager talk to a kernel. At least one reason for this is that it will cause trouble for remote sessions. It could also end up forcing the Session class to have a ton of virtual methods for abstract operations on models

**Comment by yumin** [comment]
@vibraphone I tested from cmb on both cgm and discrete, and they seem to be working. I will try to add some unit tests for the new operators later.

**Comment by yumin** [comment]
Still working on tests ...

**Pull request merged**
