### PR TITLE
Windows symbol export

### PR DESCRIPTION
**Pull request by mathstuf**
---
Also brings other Windows fixes in as well. See #141.

### CODE REVIEW

**Comment by robertmaynard** [comment]
+1 looks good to me, but I will let @vibraphone push the button.

**Comment by mathstuf** [comment]
CMB will need parallel changes. Getting through those now.

**Comment by mathstuf** [comment]
CMB changes are [here](https://gitlab.kitware.com/cmb/cmb/merge_requests/17).

**Comment by vibraphone** [comment]
+2

**Pull request merged**
