### PR TITLE
Skip header install

### PR DESCRIPTION
**Pull request by mathstuf**
---
Requires [this patch](https://gitlab.kitware.com/vtk/vtk/merge_requests/749).

@vibraphone @bradking

### CODE REVIEW

**Comment by vibraphone** [comment]
+1 as long as `vtkModelMultiBlockSource.h` and friends are still installed (presumably by SMTK and not VTK?).

**Comment by mathstuf** [comment]
They're still installed just as they've always been. Without this, they *also* went to `$prefix/include` due to the VTK module development installation mechanisms.

**Comment by vibraphone** [comment]
> They're still installed just as they've always been. Without this, they also went to $prefix/include due to the VTK module development installation mechanisms.

Some places in SMTK and CMB (including autogenerated Python wrappers, which we need) `#include "vtkModelMultiBlockSource.h"` instead of `#include "smtk/extensions/vtk/vtkModelMultiBlockSource.h"`, so we may need to add `smtk/extensions/vtk` to the `target_include_directories` for the library.

**Comment by mathstuf** [comment]
Well, these headers had never appeared in this location before, so I don't see why removing them again would break things (and CMB certainly can't cope with the headers installed here).

**Comment by mathstuf** [comment]
Rebased for `release-v1`.

**Comment by mathstuf** [comment]
Will also merge into `release-v1`.

**Pull request merged**
