### PR TITLE
Name changes to address #85.

### LINKED ISSUE #85: Consistent target and cmake option names.
SMTK's libraries and CMake options are not named consistently.

+ All of the session `*_Plugin` libraries should be `*Plugin` (no underscore).
+ All of the support libraries should be named `SMTKXXX`, not `smtkXXX` or `xxxSMTK`
     + `QtSMTK` → `SMTKQt`
     + `cgmSMTK` → `SMTKCGMSession`
     + `cgmSMTKPython` → `SMTKCGMSessionPython`
     + `smtkDiscreteSession` → `SMTKDiscreteSession`
     + `smtkDiscreteSessionPython` → `SMTKDiscreteSessionPython`
     + `SMTKSessionExodus` → `SMTKExodusSession`
     + `SMTKSessionExodusPython` → `SMTKExodusSessionPython`
     + `SMTKRemotePython` → `SMTKRemoteSessionPython`
     + `SMTKRemote` → `SMTKRemoteSession`
+ All of the CMake configuration options should be named consistently.
    + `SMTK_BUILD_QT` → `SMTK_ENABLE_QT_SUPPORT`
    + `SMTK_BUILD_VTK` → `SMTK_ENABLE_VTK_SUPPORT`
    + `SMTK_BUILD_CGM` → `SMTK_ENABLE_CGM_SESSION`
    + `SMTK_BUILD_SESSION_PLUGIN` → `SMTK_ENABLE_PARAVIEW_SUPPORT`
    + `SMTK_ENABLE_REMUS` → `SMTK_ENABLE_REMOTE_SESSION` (or perhaps in addition to `SMTK_ENABLE_REMUS_SUPPORT` if mesh workers will also be included).
    + `SMTK_BUILD_MOAB_READER` → `SMTK_ENABLE_MOAB_SUPPORT`
    + `SMTK_BUILD_DISCRETE_SESSION` → `SMTK_ENABLE_DISCRETE_SESSION`
    + `SMTK_BUILD_CGM` → `SMTK_ENABLE_CGM_SESSION`

### PR DESCRIPTION
**Pull request by vibraphone**
This should close #85, #97, and #91 .

### CODE REVIEW

**Comment by vibraphone** [comment]
This will require changes to CMB ([merge request 21](https://gitlab.kitware.com/cmb/cmb/merge_requests/21)) and the CMB superbuild ([merge request 24](https://gitlab.kitware.com/cmb/cmb-superbuild/merge_requests/24)).

**Comment by yumin** [comment]
Was this tested with Discrete session enabled? I am getting linking errors

Linking CXX shared library ../../../../lib/libvtkSMTKDiscreteModel-6.3.dylib
Undefined symbols for architecture x86_64:
  "vtkXMLParser::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtkModelXMLParser::PrintSelf(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent) in vtkModelXMLParser.cxx.o
  "vtkObjectBase::PrintHeader(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for vtkSerializableObject in vtkSerializableObject.cxx.o
      vtable for vtkSerializationHelper in vtkSerializationHelper.cxx.o
      vtable for vtkSerializationHelperMap in vtkSerializationHelperMap.cxx.o
      vtable for vtkSerializer in vtkSerializer.cxx.o
      vtable for vtkModelXMLParser in vtkModelXMLParser.cxx.o
      vtable for vtkCommonSerializationHelper in vtkCommonSerializationHelper.cxx.o
      vtable for vtkInformationKeyMap in vtkInformationKeyMap.cxx.o
      ...
  "vtkObjectBase::PrintTrailer(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, vtkIndent)", referenced from:
      vtable for vtkSerializableObject in vtkSerializableObject.cxx.o
      vtable for vtkSerializationHelper in vtkSerializationHelper.cxx.o
      vtable for vtkSerializationHelperMap in vtkSerializationHelperMap.cxx.o
      vtable for vtkSerializer in vtkSerializer.cxx.o
      vtable for vtkModelXMLParser in vtkModelXMLParser.cxx.o
      vtable for vtkCommonSerializationHelper in vtkCommonSerializationHelper.cxx.o
      vtable for vtkInformationKeyMap in vtkInformationKeyMap.cxx.o
      ...

**Comment by vibraphone** [comment]
@yumin Yes, this was tested with the discrete session (and all other sessions) enabled. Without more information, I cannot understand what is wrong, although a first guess would be that you should wipe your build+install directories clean and rebuild.

**Comment by yumin** [comment]
This is a clean smtk build on Mac 10.10.2. I also removed the old smtk libs and headers from cmbsuperbuild install. Investigating ...

**Comment by yumin** [comment]
@vibraphone A clean rebuild of cmbsuperbuild solved my build problems. Sorry for the noise, now I can move on to rebase my PRs in smtk and cmb.

**Pull request merged**
