### PR TITLE
shiboken: use response files for shiboken calls

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by vibraphone** [comment]
This is failing because Travis-CI is using a [shiboken package from LaunchPad](https://launchpad.net/~dcthomp/+archive/ubuntu/smtk) that does not include your changes. I will try to get a new package built this week.

**Comment by mathstuf** [comment]
The necessary Shiboken changes: https://github.com/OpenGeoscience/shiboken/pull/6

**Comment by robertmaynard** [comment]
@vibraphone can I merge it without travis approval?

**Comment by vibraphone** [comment]
> @vibraphone can I merge it without travis approval?

Yes, go ahead.

**Pull request merged**
